// Generated by https://quicktype.io

import { LabSettingState } from '../../../atoms/labSettingState'
import { UserSerialized } from '../types'

export type BacktestPayload = {
  title: string
  data: Omit<LabSettingState, 'nextPortfolioId'>
  returns: { x: string; y: number }[][]
  indicators: {
    id: number
    cagr: number | null
    sharpe: number | null
  }[]
}

// Generated by https://quicktype.io

export interface Backtest {
  id: number
  title: string
  body: string
  start_date: string
  end_date: string
  initial_amount: number
  cashflow_value: null | number
  cashflow_interval: null | number
  is_private: boolean
  created_at: string
  thumbnail: string
  user: UserSerialized
  portfolios: Portfolio[]
}

export interface Portfolio {
  id: number
  name: string
  body: null | string
  rebalancing: number
  cagr: number
  sharpe: number
  assets: Asset[]
}

export interface Asset {
  id: number
  ticker: string
  weight: number
  image: null | string
}
