// Generated by https://quicktype.io

export type User = {
  id: number
  email: string
  username: string | null
  display_name: string
  photo_url: string | null
  created_at: string
  is_certified: boolean
}
