// Generated by https://quicktype.io

export type User = {
  id: number
  email: string
  username: string
  display_name: string
  photo_url: string | null
  created_at: string
  is_certified: boolean
  member_id: string
}

export type UserSerialized = Omit<
  User,
  'email' | 'created_at' | 'is_certified' | 'memberId'
>
